"""Unit tests for TOSEM go/no-go truth pilots (no network)."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import pyarrow as pa
import pyarrow.parquet as pq

from artifact_lab.experiments.truth_pilots.attribution import classify_commit, scan_commit_attribution
from artifact_lab.experiments.truth_pilots.go_no_go import run_go_no_go_report
from artifact_lab.experiments.truth_pilots.references import ExtractedReference, extract_references
from artifact_lab.experiments.truth_pilots.sample import (
    family_group_for_path,
    load_instruction_commits_from_l1,
    sample_instruction_files,
)
from artifact_lab.experiments.truth_pilots.verify_refs import verify_reference


def _write_l1(tmp_path: Path, rows: list[dict]) -> Path:
    path = tmp_path / "events.parquet"
    table = pa.Table.from_pylist(
        rows,
        schema=pa.schema(
            [
                ("repo_id", pa.string()),
                ("repo_url", pa.string()),
                ("family", pa.string()),
                ("path", pa.string()),
                ("commit_sha", pa.string()),
                ("commit_time", pa.timestamp("us", tz="UTC")),
                ("author_name", pa.string()),
                ("author_email_hash", pa.string()),
                ("change_type", pa.string()),
                ("blob_sha", pa.string()),
                ("extraction_wave", pa.string()),
                ("detector_version", pa.string()),
            ]
        ),
    )
    pq.write_table(table, path)
    return path


def test_family_group_mapping():
    assert family_group_for_path("AGENTS.md") == "AGENTS.md"
    assert family_group_for_path(".cursor/rules/foo.md") == "Cursor rules"
    assert family_group_for_path("prompts/system.md") == "prompt files"


def test_extract_references_paths_commands_scripts_and_deps():
    text = """
See `src/main.py` and [docs](docs/guide.md).
Run `python scripts/run.py`:
```bash
make test
pip install pydantic
npm install lodash
bash scripts/deploy.sh
```
Directory: `tests/unit/`
"""
    refs = extract_references(text)
    texts = {(r.reference_type, r.reference_text) for r in refs}
    assert ("path", "src/main.py") in texts
    assert ("path", "docs/guide.md") in texts
    assert ("directory", "tests/unit/") in texts
    assert any(r.reference_type == "command" and "make test" in r.reference_text for r in refs)
    assert ("dependency", "pydantic") in texts
    assert any(r.reference_type == "script_name" and "scripts/run.py" in r.reference_text for r in refs)
    assert any(r.reference_type == "script_name" and "scripts/deploy.sh" in r.reference_text for r in refs)


def test_verify_reference_path_and_script(tmp_path: Path):
    repo_dir = tmp_path / "repo.git"
    repo_dir.mkdir()
    head_paths = {"src/main.py", "scripts/run.py", "README.md"}
    for ref_text in ("src/main.py", "scripts/run.py"):
        ref = ExtractedReference(reference_type="script_name", reference_text=ref_text, context="")
        status, _ = verify_reference(ref, repo_dir=repo_dir, head_paths=head_paths)
        assert status == "verified"

    missing = ExtractedReference(reference_type="path", reference_text="missing/foo.py", context="")
    status, evidence = verify_reference(missing, repo_dir=repo_dir, head_paths=head_paths)
    assert status == "missing"
    assert "HEAD" in evidence


def test_classify_agent_coauthored_and_bot():
    msg = "Update rules\n\nCo-Authored-By: Claude <noreply@anthropic.com>"
    cls, sig, evidence = classify_commit(
        author_name="Human Dev",
        author_email="dev@example.com",
        commit_message=msg,
    )
    assert cls == "agent_coauthored"
    assert sig == "co_authored_by"
    assert "co_authored_by" in evidence

    cls, sig, _ = classify_commit(
        author_name="dependabot[bot]",
        author_email="49699333+dependabot[bot]@users.noreply.github.com",
        commit_message="Bump lodash",
    )
    assert cls == "bot_author"
    assert sig == "bot_account"

    cls, _, evidence = classify_commit(
        author_name="Dev",
        author_email="dev@example.com",
        commit_message="Generated by Cursor agent",
    )
    assert cls == "agent_signature_in_message"
    assert "cursor" in evidence.lower()


def test_sample_instruction_files_stratified_deterministic(tmp_path: Path):
    ts = datetime(2024, 1, 1, tzinfo=timezone.utc)
    rows = []
    paths = [
        "AGENTS.md",
        "CLAUDE.md",
        ".cursor/rules/r1.md",
        ".github/copilot-instructions.md",
        "SKILL.md",
        "prompts/p1.md",
    ]
    for i, instr in enumerate(paths):
        rows.append(
            {
                "repo_id": f"repo{i}",
                "repo_url": f"https://github.com/org/r{i}",
                "family": "ai_conventions_v1",
                "path": instr,
                "commit_sha": f"sha{i}",
                "commit_time": ts,
                "author_name": "a",
                "author_email_hash": "h",
                "change_type": "add",
                "blob_sha": f"blob{i}",
                "extraction_wave": "test",
                "detector_version": "1.0.0",
            }
        )
    l1 = _write_l1(tmp_path, rows)
    s1 = sample_instruction_files([l1], n=5, n_min=3, n_max=6, seed=42)
    s2 = sample_instruction_files([l1], n=5, n_min=3, n_max=6, seed=42)
    assert [x.instruction_path for x in s1] == [x.instruction_path for x in s2]
    assert len(s1) == 5
    assert all(x.family_group for x in s1)


def test_load_instruction_commits_from_l1(tmp_path: Path):
    ts = datetime(2024, 1, 1, tzinfo=timezone.utc)
    rows = [
        {
            "repo_id": "r1",
            "repo_url": "https://github.com/o/r1",
            "family": "ai_conventions_v1",
            "path": "AGENTS.md",
            "commit_sha": "abc",
            "commit_time": ts,
            "author_name": "Alice",
            "author_email_hash": "h",
            "change_type": "add",
            "blob_sha": "b1",
            "extraction_wave": "test",
            "detector_version": "1.0.0",
        },
        {
            "repo_id": "r1",
            "repo_url": "https://github.com/o/r1",
            "family": "ai_conventions_v1",
            "path": "AGENTS.md",
            "commit_sha": "abc",
            "commit_time": ts,
            "author_name": "Alice",
            "author_email_hash": "h",
            "change_type": "modify",
            "blob_sha": "b2",
            "extraction_wave": "test",
            "detector_version": "1.0.0",
        },
    ]
    l1 = _write_l1(tmp_path, rows)
    commits = load_instruction_commits_from_l1([l1])
    assert len(commits) == 1
    assert commits[0].family_group == "AGENTS.md"


def test_scan_commit_attribution_human_default():
    candidate = scan_commit_attribution(
        repo_id="r",
        repo_url="https://github.com/o/r",
        instruction_path="AGENTS.md",
        commit_sha="abc",
        commit_time="1",
        author_name="Alice",
        author_email="alice@example.com",
        commit_message="docs: update agent instructions",
    )
    assert candidate.attribution_class == "human"
    assert candidate.signature_type == "none"


def test_go_no_go_report_from_fixture_csvs(tmp_path: Path):
    summary = tmp_path / "reference_summary.csv"
    summary.write_text(
        "sample_id,repo_id,instruction_path,family_group,pattern_id,total_references,"
        "verifiable_references,verified,missing,unverifiable,extraction_ok\n"
        "1,r1,AGENTS.md,AGENTS.md,agents_md,5,3,2,1,0,true\n"
        "2,r2,CLAUDE.md,CLAUDE.md,claude_md,0,0,0,0,0,true\n",
        encoding="utf-8",
    )
    p2 = tmp_path / "agent_attribution_summary.csv"
    p2.write_text(
        "metric,value\n"
        "commits_scanned,100\n"
        "instruction_files_touched,50\n"
        "candidate_agent_authored,10\n"
        "candidate_agent_coauthored,8\n"
        "files_with_agent_signal,15\n"
        "signal_rate_pct,18.0\n",
        encoding="utf-8",
    )
    report = run_go_no_go_report(output_dir=tmp_path)
    text = report.read_text(encoding="utf-8")
    assert "TOSEM Go/No-Go" in text
    assert "GO" in text
